W4D5/music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:create, :new, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end
  resources :tracks, only: [:create, :edit, :show, :update, :destroy]
end

W4D5/music_app/app/models/album.rb
class Album < ApplicationRecord
  belongs_to :band
  has_many :tracks, dependent: :destroy
end

W4D5/music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums
end

W4D5/music_app/app/models/track.rb
class Track < ApplicationRecord
  validates :ord, presence: true
  validates :title, presence: true
  belongs_to :album
end

W4D5/music_app/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 8, allow_nil: true}
  validates :password_digest, presence: {message: 'Password can\'t be blank'}

  before_validation :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil
  end
end

W4D5/music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :title, :year, :live)
  end
end

W4D5/music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :current_user_id, :logged_in?

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login_user!(user)
    session[:session_token] = user.reset_session_token!
  end
end

W4D5/music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def show
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if user.nil?
      flash.now[:errors] = ["Invalid email or password."]
      render :new
    else
      login_user!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

W4D5/music_app/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def new
    @album = Album.find(params[:album_id])
    @track = Track.new(album_id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to album_url(@track.album_id)
  end

  private

  def track_params
    params.require(:track).permit(:album_id, :title, :ord, :lyrics, :bonus)
  end
end

W4D5/music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render :show
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
      redirect_to new_session_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/music_app/app/helpers/albums_helper.rb
module AlbumsHelper
end

W4D5/music_app/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D5/music_app/app/helpers/users_helper.rb
module UsersHelper
end

W4D5/music_app/app/views/albums/_form.html.erb
<% action_url = album.persisted? ? album_url(album) : albums_url %>
<% http_method = album.persisted? ? "PATCH" : "POST" %>
<% button_text = album.persisted? ? "Update Album!" : "Create Album!" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='album-title'>Title</label>
    <input id='album-title' type="text" name="album[title]" value="<%= album.title %>">
  </p>

  <p>
    <label for='album-band'>Band</label>
    <select id='album-band' name="album[band_id]">
        <% Band.all.each do |band| %>
            <option
                <%= "selected" if album.band_id == band.id %>
                value="<%= band.id %>">
                <%= band.name %>
            </option>
        <% end %>
    </select>
  </p>

  <p>
    <label for="album_live_t">Live</label>
    <input
      type="radio"
      name="album[live]"
      value="t"
      id="album_live_t"
      <%= "checked" if album.live %>>
    <label for="album_live_f">Studio</label>
    <input
      type="radio"
      name="album[live]"
      value="f"
      id="album_live_f"
      <%= "checked" if !album.live %>>
  </p>

  <p>
    <label for='album-year'>Year</label>
    <input id='album-year' type="number" name="album[year]" value="<%= album.year %>">
  </p>

  <input type="submit" value="<%= button_text %>">
</form>

W4D5/music_app/app/views/albums/edit.html.erb
<h1 class='page-header'>Edit <%= @album.title %></h1>

<%= render "form", album: @album %>

W4D5/music_app/app/views/albums/new.html.erb
<h1 class='page-header'>New <%= @band.name %> Album.</h1>

<%= render "form", album: @album %>

W4D5/music_app/app/views/albums/show.html.erb
<h1 class='page-header'><%= @album.title %></h1>

<% if @album.tracks.length > 0 %>
<ul class='main-list'>
  <% @album.tracks.each do |track| %>
    <li><a href="<%= track_url(track) %>"><p><%= track.title %></p></a></li>
  <% end %>
</ul>
<% else %>
  <p>There are no track to be displayed.</p>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_album_track_url(@album) %>">New track</a></li>
  <li><a class='button' href="<%= edit_album_url(@album) %>">Edit album</a></li>
  <li>
    <form action="<%= album_url(@album) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Album">
    </form>
  </li>
  <li><a class='button' href="<%= band_url(@album.band) %>">Back to <%= @album.band.name %></a></li>
</ul>

W4D5/music_app/app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= band.name %>">
  </p>

  <input type="submit">
</form>

W4D5/music_app/app/views/bands/edit.html.erb
<h1 class='page-header'>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>

W4D5/music_app/app/views/bands/index.html.erb
<h1 class='page-header'>Bands</h1>

<ul class='main-list'>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
  <% end %>
</ul>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_url %>" >New band</a></li>
</ul>

W4D5/music_app/app/views/bands/new.html.erb
<h1 class='page-header'>New band.</h1>

<%= render "form", band: @band %>

W4D5/music_app/app/views/bands/show.html.erb
<h1 class='page-header'><%= @band.name %></h1>

<h4 class='sub-header'>Albums</h4>

<% if @band.albums.length > 0 %>
  <ul class='main-list'>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><p><%= album.title %></p></a></li>
  <% end %>
  </ul>
<% else %>
  <p>There are no albums to display.</p>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_album_url(@band) %>">New album</a></li>
  <li><a class='button' href="<%= edit_band_url(@band) %>">Edit band</a></li>
  <li>
    <form action="<%= band_url(@band) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Band">
    </form>
  </li>
  <li><a class='button' href="<%= bands_url %>">All bands</a></li>
</ul>

W4D5/music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <nav>
        <div class='user-detail'>
          <p>Logged in as: <%= current_user.email %></p>
        <form action=<%= session_url %> method='post'>
          <input
            type="hidden"
            name="_method"
            value="delete">
          <input
            type="hidden"
            name="authenticity_token"
            value="<%= form_authenticity_token %>">
          <input
            type="submit" value="Sign Out">
        </form>
        </div>
      </nav>
    <% end %>

    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:errors] %>
      <p><%= flash[:errors].join(", ") %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

W4D5/music_app/app/views/tracks/_form.html.erb
<% action_url = track.persisted? ? track_url(track) : tracks_url %>
<% http_method = track.persisted? ? "PATCH" : "POST" %>


<form class='form' action="<%= action_url %>" method="POST" %>
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label for='track-name'>Name</label>
  <input id='track-name' type="text" name="track[title]" value="<%= track.title %>">
</p>

<p>
<label for='track-album'>Album</label>
  <select id='track-album' name="track[album_id]">
    <% Album.all.each do |album| %>
      <option
        <%= "selected" if track.album_id == album.id %>
        value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>
</p>

<p>
  <label>Ord
  <input type="number" name="track[ord]" value="<%= track.ord %>">
  </label>
</p>

<p>
  <label for="track_bonus_f">Standard</label>
  <input
    type="radio"
    name="track[bonus]"
    value="f"
    id="track_bonus_f"
    <%= "checked" if !track.bonus %>>
  <br>
  <label for="track_bonus_t">Bonus</label>
  <input
    type="radio"
    name="track[bonus]"
    value="t"
    id="track_bonus_t"
    <%= "checked" if track.bonus %>>
</p>

<p>
  <label for="track_lyrics">Lyrics</label><br>
  <textarea id="track_lyrics"
    rows="10" cols="40"
    name="track[lyrics]"><%= track.lyrics %></textarea>
</p>

  <input type="submit">
</form>

W4D5/music_app/app/views/tracks/edit.html.erb
<h1 class='page-header'>Edit <%= @track.title %></h1>

<%= render "form", track: @track %>

W4D5/music_app/app/views/tracks/new.html.erb
<h1 class='page-header'>New <%= @album.title %> Track.</h1>

<%= render "form", track: @track %>

W4D5/music_app/app/views/tracks/show.html.erb
<h1 class='page-header'><%= @track.title %></h1>



<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= edit_track_url(@track) %>">Edit track</a></li>
  <li>
    <form action="<%= track_url(@track) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Track">
    </form>
  </li>
  <li><a class='button' href="<%= album_url(@track.album) %>">Back to <%= @track.album.title %></a></li>
</ul>